# Generated by Django 3.1.7 on 2021-03-30 19:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bio', models.TextField(blank=True, default='')),
                ('graduation_year', models.IntegerField(blank=True, default=2021, null=True, validators=[django.core.validators.MinValueValidator(2021), django.core.validators.MaxValueValidator(2025)])),
                ('pronouns', models.CharField(blank=True, max_length=50)),
                ('phone_number', phone_field.models.PhoneField(blank=True, max_length=14)),
                ('on_grounds', models.CharField(blank=True, choices=[('on-grounds', 'On-Grounds'), ('off-grounds', 'Off-Grounds'), ('no preference', 'No Preference')], max_length=50)),
                ('max_price', models.IntegerField(blank=True, default=600, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
