# Generated by Django 3.1.7 on 2021-03-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=True),
        ),
    ]
