# Generated by Django 3.1.7 on 2021-04-03 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
