# Generated by Django 3.1.7 on 2021-04-06 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210404_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
