# Generated by Django 3.1.7 on 2021-03-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210325_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
