# Generated by Django 3.1.7 on 2021-03-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='on_grounds',
            field=models.CharField(blank=True, choices=[('on-grounds', 'On-Grounds'), ('off-grounds', 'Off-Grounds'), ('no preference', 'No Preference')], max_length=50),
        ),
    ]
