# Generated by Django 3.1.7 on 2021-04-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210407_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_type',
            field=models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Townhouse', 'Townhouse'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnished',
            field=models.CharField(blank=True, choices=[('Furnished', 'Furnished'), ('Unfurnished', 'Unfurnished')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='room_type',
            field=models.CharField(blank=True, choices=[('Single', 'Single Room'), ('Double', 'Double Room'), ('Either', 'Either Single or Double')], max_length=50),
        ),
    ]
