# Generated by Django 3.1.7 on 2021-03-25 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_on_grounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_price',
            field=models.IntegerField(blank=True, default=600, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
