# Generated by Django 3.1.7 on 2021-03-25 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_max_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
