# Generated by Django 3.1.7 on 2021-03-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210325_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=2021),
        ),
    ]
