# Generated by Django 3.1.7 on 2021-04-10 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210410_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lease_duration',
            field=models.IntegerField(blank=True, default=12, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(72)], verbose_name='Lease Duration (Months)'),
        ),
    ]
