# Generated by Django 3.1.7 on 2021-03-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210325_2113'),
        ('users', '0013_auto_20210325_2236'),
    ]

    operations = [
    ]
