# Generated by Django 3.1.7 on 2021-04-13 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210410_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='max_price',
            field=models.IntegerField(blank=True, default=600, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Max Rent'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='on_grounds',
            field=models.CharField(blank=True, choices=[('on-grounds', 'On-Grounds'), ('off-grounds', 'Off-Grounds'), ('no preference', 'No Preference'), ('na', 'N/A')], max_length=50),
        ),
    ]
