# Generated by Django 3.1.7 on 2021-04-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210413_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='match_list',
            field=models.CharField(blank=True, choices=[('Property', 'Property'), ('Profile', 'Profile'), ('Both', 'Both')], max_length=100),
        ),
    ]
