# Generated by Django 3.1.7 on 2021-03-26 02:50

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210326_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=14),
        ),
    ]
