# Generated by Django 3.1.7 on 2021-03-28 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210328_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=2021, null=True, validators=[django.core.validators.MinValueValidator(2021), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
