# Generated by Django 3.1.7 on 2021-04-27 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210415_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_profile',
            field=models.BooleanField(blank=True, default=False, verbose_name='Make Profile Public'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_price',
            field=models.IntegerField(blank=True, default=600, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Max Rent or Rent Amount'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='on_grounds',
            field=models.CharField(blank=True, choices=[('On-grounds', 'On-Grounds'), ('Off-grounds', 'Off-Grounds'), ('No preference', 'No Preference')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pref_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('No preference', 'No preference')], max_length=30, verbose_name='Preferred Gender'),
        ),
        migrations.AlterField(
            model_name='property',
            name='display_property',
            field=models.BooleanField(blank=True, default=False, verbose_name='Make Property Public'),
        ),
        migrations.AlterField(
            model_name='property',
            name='on_grounds',
            field=models.CharField(blank=True, choices=[('On-Grounds', 'On-Grounds'), ('Off-Grounds', 'Off-Grounds')], max_length=50, verbose_name='On-Grounds or Off-Grounds?'),
        ),
    ]
