# Generated by Django 3.1.7 on 2021-04-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210427_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_profile',
            field=models.BooleanField(blank=True, default=False, verbose_name='MAKE PROFILE PUBLIC'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='on_grounds',
            field=models.CharField(blank=True, choices=[('On-grounds', 'On-Grounds'), ('Off-grounds', 'Off-Grounds'), ('No preference', 'No Preference')], max_length=50, verbose_name='On-Grounds or Off-Grounds?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='display_property',
            field=models.BooleanField(blank=True, default=False, verbose_name='MAKE PROPERTY PUBLIC'),
        ),
    ]
