# Generated by Django 3.1.7 on 2021-03-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_profile_graduation_year'),
        ('users', '0020_profile_graduation_year'),
    ]

    operations = [
    ]
