# Generated by Django 3.2 on 2021-05-06 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210429_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pref_gender',
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('No preference', 'No preference')], max_length=30, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='property',
            name='current_number_of_roommates',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
