# Generated by Django 3.2 on 2021-05-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210505_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pref_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('No preference', 'No preference')], max_length=30, verbose_name='Preferred Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=30, verbose_name='Gender'),
        ),
    ]
